# Generated by Django 5.0.4 on 2024-04-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время последней рассылки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esender.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='server_response',
            field=models.CharField(blank=True, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.BooleanField(verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='client',
            field=models.ManyToManyField(to='Esender.client', verbose_name='Клиенты рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='date_and_time',
            field=models.DateField(verbose_name='Дата и время первой рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='Esender.message', verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='period',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Запущена', 'Запущена'), ('Создана', 'Создана'), ('Завершена', 'Завершена')], max_length=50, verbose_name='Статус'),
        ),
    ]
